import { Router } from "express";
import { requireAuth } from "../middlewares/auth";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import studentsRouter from "./students";
import staffRouter from "./staff";
import classesRouter from "./classes";
import subjectsRouter from "./subjects";
import attendanceRouter from "./attendance";
import examsRouter from "./exams";
import feesRouter from "./fees";
import hostelRouter from "./hostel";
import transportRouter from "./transport";
import announcementsRouter from "./announcements";
import complaintsRouter from "./complaints";
import vendorsRouter from "./vendors";
import materialsRouter from "./materials";
import admissionsRouter from "./admissions";
import leavesRouter from "./leaves";
import timetableRouter from "./timetable";
import visitorsRouter from "./visitors";
import libraryRouter from "./library";
import behaviorLogsRouter from "./behavior-logs";
import inventoryRouter from "./inventory";
import storageRouter from "./storage";
import notificationsRouter from "./notifications";
import salariesRouter from "./salaries";
const router = Router();
router.use(healthRouter);
router.use(authRouter);
// All routes mounted below this line require an authenticated session.
// Per-route requireRole(...) calls then enforce role allow-lists; routes
// without an explicit role guard are accessible to any authenticated user.
router.use(requireAuth);
router.use(dashboardRouter);
router.use(studentsRouter);
router.use(salariesRouter);
router.use(staffRouter);
router.use(classesRouter);
router.use(subjectsRouter);
router.use(attendanceRouter);
router.use(examsRouter);
router.use(feesRouter);
router.use(hostelRouter);
router.use(transportRouter);
router.use(announcementsRouter);
router.use(complaintsRouter);
router.use(vendorsRouter);
router.use(materialsRouter);
router.use(admissionsRouter);
router.use(leavesRouter);
router.use(timetableRouter);
router.use(visitorsRouter);
router.use(libraryRouter);
router.use(behaviorLogsRouter);
router.use(inventoryRouter);
router.use(storageRouter);
router.use(notificationsRouter);
export default router;
